import{a as d,S as p,i as g}from"./assets/vendor-64b55ca9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function c(e){if(e.ep)return;e.ep=!0;const a=i(e);fetch(e.href,a)}})();const y="42355472-3aa41b7abe4d1083b6d3aff39";d.defaults.baseURL="https://pixabay.com";d.defaults.params={key:y,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};async function h(r,t){const{data:i}=await d.get("api/",{params:{q:r,page:t}});return{images:i.hits,totalImages:i.totalHits}}const b=new p(".gallery a",{captionsData:"alt",captionDelay:250}),o={page:1,query:"",cardHeight:0},s={form:document.querySelector("form"),input:document.querySelector("input"),gallery:document.querySelector(".gallery"),loadMore:document.querySelector(".load-more")};s.form.addEventListener("submit",L);s.loadMore.addEventListener("click",q);function l({message:r,type:t="error"}){g[t]({message:r,position:"topRight"})}function u(r=!0){s.loadMore.classList.toggle("is-hidden",!r)}async function f(){try{const{images:r,totalImages:t}=await h(o.query,o.page);if(!r.length){l({message:"Sorry, there are no images matching your search query. Please try again."});return}o.page===1&&l({message:`Hooray! We found ${t} images.`,type:"success"}),s.gallery.insertAdjacentHTML("beforeend",v(r)),b.refresh(),u(o.page<Math.ceil(t/40)),o.cardHeight=s.gallery.firstElementChild.clientHeight,window.scrollBy({top:o.cardHeight-200,behavior:"smooth"})}catch{l({message:"We're sorry, but you've reached the end of search results."}),u(!1)}}function L(r){r.preventDefault(),u(!1),s.gallery.innerHTML="";const t=s.input.value.trim();if(!t){l({message:"Please enter a search query."});return}o.query=t,o.page=1,f()}function q(){o.page++,f()}function v(r){return r.map(({largeImageURL:t,webformatURL:i,likes:c,views:e,comments:a,downloads:n,tags:m})=>`
    <a class="photo-card" href="${t}">
      <img src="${i}" alt="${m}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes</b> ${c}</p>
        <p class="info-item"><b>Views</b> ${e}</p>
        <p class="info-item"><b>Comments</b> ${a}</p>
        <p class="info-item"><b>Downloads</b> ${n}</p>
      </div>
    </a>`).join("")}
//# sourceMappingURL=commonHelpers.js.map
